<?php

namespace App\Domains\Marketplace\Models;

use App\Domains\Tenancy\Concerns\BelongsToTenant;
use App\Models\Product;
use App\Models\Variant;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * What one vendor charges for one catalogue variant, and how many it has
 * (§10: Vendor Offer, owner = Vendor).
 *
 * The platform still owns the product: its title, brand, colourway and size
 * are the canonical ones, and two vendors selling the same shoe are two rows
 * here against one variant. That is what makes "who is cheapest for this size"
 * a query.
 */
class VendorOffer extends Model
{
    use BelongsToTenant, HasFactory;

    // sellable_stock is generated by the database, exactly as on variants.
    protected $guarded = ['sellable_stock'];

    protected function casts(): array
    {
        return [
            'price' => 'integer',
            'compare_at_price' => 'integer',
            'stock_on_hand' => 'integer',
            'stock_reserved' => 'integer',
            'sellable_stock' => 'integer',
            'commission_rate_bps' => 'integer',
        ];
    }

    public static function tenantKind(): string
    {
        return 'vendor';
    }

    public static function tenantColumn(): string
    {
        return 'vendor_id';
    }

    public function vendor(): BelongsTo
    {
        return $this->belongsTo(Vendor::class);
    }

    public function variant(): BelongsTo
    {
        return $this->belongsTo(Variant::class);
    }

    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class);
    }

    /** Offers a customer may actually buy right now. */
    public function scopeSellable(Builder $query): Builder
    {
        return $query->where('status', 'active')->where('sellable_stock', '>', 0);
    }

    public function isSellable(): bool
    {
        return $this->status === 'active' && $this->sellable_stock > 0;
    }

    public function hasActivePromotion(): bool
    {
        return $this->compare_at_price !== null && $this->compare_at_price > $this->price;
    }

    public function discountPercent(): ?int
    {
        if (! $this->hasActivePromotion()) {
            return null;
        }

        return (int) round(($this->compare_at_price - $this->price) / $this->compare_at_price * 100);
    }
}
