<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Price and stock stop belonging to a variant and start belonging to a branch.
 *
 * Until now a shoe had one price and one pile of stock, which was true while
 * there was one shop. §14 and §16 say otherwise: a franchise sets its own
 * price inside the policy central gives it, and holds its own stock. Shiraz
 * selling from Tehran's shelf is the failure this removes.
 *
 * Two tables rather than one, because they change for different reasons and at
 * different rates. A price is an editorial decision made occasionally by a
 * person and audited (§29). Stock moves on every sale, is written by the
 * checkout under a row lock, and is explained by its ledger. Putting them in
 * one row would mean every sale touches the priced row, and every price change
 * contends with the till.
 *
 * This migration only adds and copies. Nothing is dropped here — the columns it
 * copies from are removed by the migration immediately after, so that if the
 * backfill is wrong the data is still in its old place to compare against.
 */
return new class extends Migration
{
    public function up(): void
    {
        /*
         * What a branch sells a variant for.
         *
         * A variant with no row here is not sold by that branch. That is the
         * useful default: a franchise opens with an empty shop and lists what
         * it actually stocks, rather than inheriting the whole catalogue and
         * having to hide most of it.
         */
        Schema::create('branch_offers', function (Blueprint $table) {
            $table->id();
            $table->foreignId('branch_id')->constrained()->cascadeOnDelete();
            $table->foreignId('variant_id')->constrained()->cascadeOnDelete();

            // Integer Rial, as everywhere else. Money is never floated.
            $table->unsignedBigInteger('price');
            $table->unsignedBigInteger('compare_at_price')->nullable();

            // What this branch paid. Per branch, not per variant: two branches
            // buying the same shoe from different suppliers pay differently,
            // and a margin computed from somebody else's cost is fiction.
            $table->unsignedBigInteger('cost_price')->nullable();

            // Whether the branch is currently selling it. Distinct from
            // variants.status, which says whether the SKU exists at all: a
            // branch pausing a line must not delist it for everybody.
            $table->enum('status', ['active', 'inactive'])->default('active');

            $table->timestamp('promotion_starts_at')->nullable();
            $table->timestamp('promotion_ends_at')->nullable();
            $table->timestamps();

            // One offer per variant per branch. Two prices for one shoe in one
            // shop is not a state worth writing code to resolve.
            $table->unique(['branch_id', 'variant_id']);

            // The storefront's own query: this branch, everything sellable.
            $table->index(['branch_id', 'status']);
            $table->index('variant_id');
        });

        /*
         * What a branch physically has.
         *
         * The same shape the variant carried, with the same invariants, moved
         * down a level. sellable_stock stays generated by the database so no
         * application path can disagree with it (§31).
         */
        Schema::create('branch_inventory', function (Blueprint $table) {
            $table->id();
            $table->foreignId('branch_id')->constrained()->cascadeOnDelete();
            $table->foreignId('variant_id')->constrained()->cascadeOnDelete();

            $table->integer('stock_on_hand')->default(0);
            $table->integer('stock_reserved')->default(0);
            $table->integer('sellable_stock')->storedAs('stock_on_hand - stock_reserved');

            // Below this the branch's panel calls it low. Per branch because a
            // warehouse and a shop mean different things by "nearly out".
            $table->unsignedInteger('low_stock_threshold')->default(0);
            $table->timestamps();

            $table->unique(['branch_id', 'variant_id']);
            $table->index(['branch_id', 'sellable_stock']);
        });

        // The invariants that were on variants, now one level down. They are
        // constraints rather than checks in PHP for the reason they always
        // were: application-level checks lose the race under concurrency, and
        // overselling is the failure §16.2 refuses to accept.
        DB::statement('ALTER TABLE branch_inventory ADD CONSTRAINT branch_inventory_on_hand_not_negative CHECK (stock_on_hand >= 0)');
        DB::statement('ALTER TABLE branch_inventory ADD CONSTRAINT branch_inventory_reserved_not_negative CHECK (stock_reserved >= 0)');
        DB::statement('ALTER TABLE branch_inventory ADD CONSTRAINT branch_inventory_reserved_within_on_hand CHECK (stock_reserved <= stock_on_hand)');
        DB::statement('ALTER TABLE branch_offers ADD CONSTRAINT branch_offers_compare_at_above_price CHECK (compare_at_price IS NULL OR compare_at_price >= price)');
        DB::statement('ALTER TABLE branch_offers ADD CONSTRAINT branch_offers_promotion_window_ordered CHECK (promotion_starts_at IS NULL OR promotion_ends_at IS NULL OR promotion_ends_at > promotion_starts_at)');

        /*
         * The ledger belongs to a branch too.
         *
         * Nullable for the length of this migration only — there are rows
         * already, and they have to be given an owner before the column can be
         * required.
         */
        Schema::table('inventory_movements', function (Blueprint $table) {
            $table->foreignId('branch_id')->nullable()->after('id')->constrained()->cascadeOnDelete();
            $table->index(['branch_id', 'variant_id', 'created_at']);
        });

        $this->backfill();

        DB::statement('ALTER TABLE inventory_movements ALTER COLUMN branch_id SET NOT NULL');
    }

    /**
     * Everything the shop already had becomes the central branch's.
     *
     * That is the whole content of the "the main store is the central branch"
     * decision: there is no separate central pricing mechanism to keep in step
     * with the franchise one, because the main store uses the franchise one.
     */
    private function backfill(): void
    {
        $central = DB::table('branches')->where('type', 'central')->value('id');

        if ($central === null) {
            // Nothing to move on a fresh database — the seeders will create
            // the branch and the catalogue in the right order. But variants
            // with no branch to give them to would be silently dropped by the
            // next migration, and losing every price in the shop deserves a
            // stop rather than a shrug.
            if (DB::table('variants')->exists()) {
                throw new RuntimeException(
                    'There are variants to move but no central branch to move them to. '
                    .'Run `php artisan db:seed --class=BranchSeeder` first, then migrate again.'
                );
            }

            return;
        }

        DB::statement('
            INSERT INTO branch_offers
                (branch_id, variant_id, price, compare_at_price, cost_price, status,
                 promotion_starts_at, promotion_ends_at, created_at, updated_at)
            SELECT ?, id, price, compare_at_price, cost_price, status,
                   promotion_starts_at, promotion_ends_at, now(), now()
            FROM variants
        ', [$central]);

        DB::statement('
            INSERT INTO branch_inventory
                (branch_id, variant_id, stock_on_hand, stock_reserved, created_at, updated_at)
            SELECT ?, id, stock_on_hand, stock_reserved, now(), now()
            FROM variants
        ', [$central]);

        DB::table('inventory_movements')->whereNull('branch_id')->update(['branch_id' => $central]);
    }

    public function down(): void
    {
        // Putting the columns back is the other migration's job; by the time
        // this runs they exist again and are empty, so the values go home
        // before the tables that hold them disappear.
        if (Schema::hasColumn('variants', 'price')) {
            DB::statement('
                UPDATE variants v SET
                    price = o.price,
                    compare_at_price = o.compare_at_price,
                    cost_price = o.cost_price,
                    promotion_starts_at = o.promotion_starts_at,
                    promotion_ends_at = o.promotion_ends_at
                FROM branch_offers o
                JOIN branches b ON b.id = o.branch_id AND b.type = \'central\'
                WHERE o.variant_id = v.id
            ');

            DB::statement('
                UPDATE variants v SET
                    stock_on_hand = i.stock_on_hand,
                    stock_reserved = i.stock_reserved
                FROM branch_inventory i
                JOIN branches b ON b.id = i.branch_id AND b.type = \'central\'
                WHERE i.variant_id = v.id
            ');
        }

        Schema::table('inventory_movements', function (Blueprint $table) {
            $table->dropForeign(['branch_id']);
            $table->dropIndex(['branch_id', 'variant_id', 'created_at']);
            $table->dropColumn('branch_id');
        });

        Schema::dropIfExists('branch_inventory');
        Schema::dropIfExists('branch_offers');
    }
};
