<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * A vendor's offer against a catalogue variant (architecture §10).
 *
 * The data ownership table answers the first open decision in §11: the
 * platform owns "Product Core" — the canonical identity of a shoe, its brand,
 * its colourways and sizes — and the vendor owns price, stock and
 * availability. So a vendor does not get its own copy of a product. It gets a
 * row here, and two vendors offering the same shoe are two rows against one
 * variant, which is the only arrangement in which "who is cheapest" is a
 * query rather than a guess.
 *
 * Stock mirrors `variants`: on hand and reserved are stored, sellable is
 * generated by the database so nothing in the application can disagree with
 * it, and the same non-negative constraints apply.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('vendor_offers', function (Blueprint $table) {
            $table->id();
            $table->foreignId('vendor_id')->constrained()->cascadeOnDelete();
            $table->foreignId('variant_id')->constrained()->cascadeOnDelete();
            // Denormalised so a vendor's product list, the commonest query in
            // the panel, does not need a join through variants.
            $table->foreignId('product_id')->constrained()->cascadeOnDelete();

            // The vendor's own stock-keeping code, which need not match ours.
            $table->string('vendor_sku')->nullable();

            $table->unsignedBigInteger('price');
            $table->unsignedBigInteger('compare_at_price')->nullable();

            $table->integer('stock_on_hand')->default(0);
            $table->integer('stock_reserved')->default(0);
            $table->integer('sellable_stock')->storedAs('stock_on_hand - stock_reserved');

            // 'draft' is the vendor's own work in progress; 'active' is on
            // sale; 'paused' keeps the row and its stock but hides it.
            $table->enum('status', ['draft', 'active', 'paused'])->default('draft');

            // Per-offer commission override. Null falls back to the rule
            // chain in commission_rules, then to the platform default.
            $table->unsignedSmallInteger('commission_rate_bps')->nullable();

            $table->unsignedSmallInteger('handling_days')->default(1);
            $table->timestamps();

            // One vendor cannot offer the same variant twice.
            $table->unique(['vendor_id', 'variant_id']);
            $table->index(['vendor_id', 'status']);
            $table->index(['variant_id', 'status']);
            $table->index(['product_id', 'status']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('vendor_offers');
    }
};
