<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('variants', function (Blueprint $table) {
            $table->id();
            $table->foreignId('product_id')->constrained()->cascadeOnDelete();
            $table->string('sku')->unique();
            $table->string('barcode')->nullable();

            // display_color is what the customer reads ("Light Smoke Grey");
            // color_family is the standardised value the colour filter uses.
            // Conflating the two is the defect called out in spec 3.3.
            $table->string('display_color');
            $table->string('color_family');

            $table->string('size_system')->default('EU');
            $table->string('size_value');
            $table->string('width')->nullable();

            // Money is stored in integer Rial to keep arithmetic exact.
            $table->unsignedBigInteger('price');
            $table->unsignedBigInteger('compare_at_price')->nullable();
            $table->unsignedBigInteger('cost_price')->nullable();

            // sellable_stock is derived (on_hand - reserved) and generated by
            // the database so no application path can disagree with it
            // (spec 4.4).
            $table->integer('stock_on_hand')->default(0);
            $table->integer('stock_reserved')->default(0);
            $table->integer('sellable_stock')->storedAs('stock_on_hand - stock_reserved');

            $table->enum('status', ['active', 'inactive'])->default('active');
            $table->timestamp('promotion_starts_at')->nullable();
            $table->timestamp('promotion_ends_at')->nullable();
            $table->unsignedInteger('weight_grams')->nullable();
            $table->timestamps();

            // A model cannot carry the same colour and size twice.
            $table->unique(['product_id', 'display_color', 'size_value']);
            $table->index(['product_id', 'color_family']);
            $table->index(['color_family', 'size_value']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('variants');
    }
};
