<?php

namespace App\Models;

use App\Models\Concerns\BelongsToBranch;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * What one branch physically has of one variant.
 *
 * `sellable_stock` is generated by the database from on_hand - reserved, so
 * there is no code path that can hold a different opinion about it. Nothing
 * may write to it.
 *
 * Deliberately **not** audited. §29 asks for a trail of manual stock
 * adjustments, and that is what `inventory_movements` is — every receipt,
 * sale, reservation and release, with its reason. Auditing this row as well
 * would write a second copy of the same story for every sale and bury the
 * decisions somebody actually needs to find.
 */
class BranchInventory extends Model
{
    use BelongsToBranch, HasFactory;

    /**
     * Stock, not stocks. Eloquent would pluralise the class to
     * `branch_inventories`, which is not a word anybody would go looking for.
     */
    protected $table = 'branch_inventory';

    protected $fillable = [
        'branch_id', 'variant_id', 'stock_on_hand', 'stock_reserved', 'low_stock_threshold',
    ];

    protected function casts(): array
    {
        return [
            'stock_on_hand' => 'integer',
            'stock_reserved' => 'integer',
            'sellable_stock' => 'integer',
            'low_stock_threshold' => 'integer',
        ];
    }

    public function variant(): BelongsTo
    {
        return $this->belongsTo(Variant::class);
    }

    public function scopeSellable(Builder $query): Builder
    {
        return $query->where('sellable_stock', '>', 0);
    }

    public function isLow(): bool
    {
        return $this->low_stock_threshold > 0 && $this->sellable_stock <= $this->low_stock_threshold;
    }
}
