{{--
    The storefront shell.

    The regions it pulls in are ported straight from
    download-version/shoe-shop-rtl.html and regenerated by theme/make-blade.js;
    this file is hand-written and is what decides their order. That order is
    the page's DOM order as measured, so moving an include here moves the
    element on the page.

    The stylesheets in the head are the template's RTL build, which is why the
    direction is fixed here rather than derived from the locale.
--}}
<!doctype html>
<html class="no-js" lang="fa" dir="rtl">

<head>
{{--
    **What this page is, for the machines that ask.**

    ترب, twice in four days: «لینک‌های ارسالی شما همچنان فاقد محصول می‌باشند و
    محتوای کالا در آن‌ها یافت نمی‌شود. این موارد مربوط به زیرساخت سایت شماست.»
    Measured from a runner against a live, in-stock product page on 19 Sept:
    `<title>VikyPlus</title>`, no og:title, no canonical, no JSON-LD, no
    itemprop, and the site-wide sentence as the description. The shoe's name
    and its price were on the page as words for a person and in none of the
    places a program is meant to look, so «محتوای کالا یافت نمی‌شود» was a
    literally accurate description of this site.

    Two hooks, and they are here rather than in `partials/head.blade.php`
    because that file is generated by `theme/make-blade.js` and a hand
    correction in it is deleted the next time the script runs.

    `@yield('meta')` is the easy half: canonical, Open Graph and the JSON-LD
    block, appended after everything. Nothing in it is a stylesheet or a script
    that runs, so the design gate still sits directly under the links it
    vouches for.

    The description is the awkward half. The generated head carries the shop's
    own sentence, which is the right answer for most pages here and the wrong
    one for a page about a single shoe — and a second `<meta name="description">`
    would not replace the first, it would sit under it, and a crawler reading
    the first would learn nothing it did not already know. So the page's own
    sentence is swapped into the tag that is already there, once, and a page
    that defines no `description` section renders the head byte for byte as
    the generator wrote it. That last part is what keeps `check-parity.js` at
    zero.
--}}
@php
    $vpHead = view('partials.head')->render();
    $vpOwnDescription = trim($__env->yieldContent('description'));

    if ($vpOwnDescription !== '') {
        $vpHead = preg_replace(
            '~<meta name="description" content="[^"]*">~u',
            '<meta name="description" content="'.e($vpOwnDescription).'">',
            $vpHead,
            1
        );
    }
@endphp
{!! $vpHead !!}
@yield('meta')
</head>

<body class="shoe-shop @yield('body-class')">

@include('partials.chrome')
@include('partials.mini-cart')
@include('partials.mobile-menu')

{{-- «این صفحه نباید هدر داشته باشه» — a page can leave the header out by
     defining `no-header`. The drawer and the mini basket above are still
     included: they are parked off-screen and cost nothing, and leaving them
     out would break the scripts that expect to find them. A page that does
     this has to carry its own way back — the basket's is «ادامه خرید». --}}
@sectionMissing('no-header')
@include('partials.header')
@endif

@yield('content')

@include('partials.footer')
@include('partials.whatsapp')
@include('partials.scripts')

</body>

</html>
