{{--
    The storefront shell.

    The regions it pulls in are ported straight from
    download-version/shoe-shop-rtl.html and regenerated by theme/make-blade.js;
    this file is hand-written and is what decides their order. That order is
    the page's DOM order as measured, so moving an include here moves the
    element on the page.

    The stylesheets in the head are the template's RTL build, which is why the
    direction is fixed here rather than derived from the locale.
--}}
<!doctype html>
<html class="no-js" lang="fa" dir="rtl">

<head>
@include('partials.head')
</head>

<body class="shoe-shop @yield('body-class')">

@include('partials.chrome')
@include('partials.mini-cart')
@include('partials.mobile-menu')

{{-- «این صفحه نباید هدر داشته باشه» — a page can leave the header out by
     defining `no-header`. The drawer and the mini basket above are still
     included: they are parked off-screen and cost nothing, and leaving them
     out would break the scripts that expect to find them. A page that does
     this has to carry its own way back — the basket's is «ادامه خرید». --}}
@sectionMissing('no-header')
@include('partials.header')
@endif

@yield('content')

@include('partials.footer')
@include('partials.whatsapp')
@include('partials.scripts')

</body>

</html>
